### PR TITLE
[Potential Feature] Render help to SVG, HTML, or colored text file

### PR DESCRIPTION
**Pull request by michelcrypt4d4mus**
This PR isn't meant to be merged as is; opening it more as a discussion to see if it's a feature you want and if so, whether env vars are a good way to implement it. I'm open to whatever yr preferences are as far as to how exactly to organize the code if so.  (my $0.02 is that moving it out to a separate `.py` file seems like potentially a good idea).

I wrote this feature into my local fork of `rich-argparse` to enable me to easily dump a rendered SVG of the help output which I then use Inkscape to convert to a png in my repo to show off the colored help. [Example can be found here](https://github.com/michelcrypt4d4mus/yaralyzer#usage).

here's the bash script I'm using to do the dump and render
```bash
RENDERED_FILE_BASE=yaralyze_help
RENDERED_SVG="$RENDERED_FILE_BASE.svg"
RENDERED_PNG="doc/rendered_images/$RENDERED_FILE_BASE.png"
export RENDER_HELP_FORMAT=svg

yaralyze -h
inkscape --export-filename="$RENDERED_PNG" "$RENDERED_SVG"
rm $RENDERED_SVG
```

btw i like where you landed on the default styling!

### CODE REVIEW

**Comment by hamdanal** [comment]
> This PR isn't meant to be merged as is; opening it more as a discussion to see if it's a feature you want and if so, whether env vars are a good way to implement it.

No sorry I don't think this belongs in this module.

> I'm open to whatever yr preferences are as far as to how exactly to organize the code if so. (my $0.02 is that moving it out to a separate `.py` file seems like potentially a good idea).

I don't indent in splitting the code in more than one file.

> I wrote this feature into my local fork of `rich-argparse` to enable me to easily dump a rendered SVG of the help output

You don't need to patch the formatter to create your svg. A much easier and cleaner way is to use the text returned by `parser.format_help()` -- something like this in a "Tools" script:
```python
from your_cli_parsing_module import parser
from rich.console import Console
from rich.text import Text
help_text = Text.from_ansi(parser.format_help())
console = Console(record=True)
with console.capture():
    console.print(help_text)
console.save_svg("your_svg_file.svg")
```

> btw i like where you landed on the default styling!

Thanks.

**Comment by hamdanal** [comment]
Sorry this didn't work out. Please consider opening an issue before contributing a feature next time. It would be much better to discuss features before the spending time implementing them.

**Comment by michelcrypt4d4mus** [comment]
no worries; like i said this wasn't necessarily meant to be merged/i opened the PR for discussion before doing a "real" implementation. it's just a hack i've been using to automate rendering the help but your approach is definitely better.

i think it could make sense to put the script from [your comment above](https://github.com/hamdanal/rich-argparse/pull/26#issuecomment-1267521906) in the README somewhere. what do you think?

**Comment by hamdanal** [comment]
> i think it could make sense to put the script from https://github.com/hamdanal/rich-argparse/pull/26#issuecomment-1267521906 in the README somewhere. what do you think?

The readme only showcases `RichHelpFormatter` features. This is a rich feature that is not related to the formatter. It could go in a “Show and tell” discussion. I can open discussions for this repo if you are interested in showing such useful stuff

**Comment by michelcrypt4d4mus** [comment]
It's up to you where something like that would live but I think if people were able to easily find the instructions they would probably make use of them to snazz up their repo with some rendered help. 90% of people won't look anywhere besides `README.md` (and things that are linked from `README.md`)

**Pull request closed without merging**
