### PR TITLE
Fix to bug that prevents usage highlighting if any metavar spans within multiple lines

### LINKED ISSUE #125: [BUG] Usage without highlighting if any metavar spans within multiple lines
### Decription of the bug
The `Usage: ...` string does not get coloured with proper highlighting styles if any metavar string spans within multiple lines.
This can happen, for example, when a mutual exclusive option is defined and the terminal window is not wide enough to display the whole metavar arguments within a single line.

### How to reproduce the error
To reproduce the error, you can run the following script:
```py
import argparse
from rich_argparse import RichHelpFormatter
import sys

# Create the format class
class SmallWidthFormmater(RichHelpFormatter):
    """
    Class to format argparse Help and Description using the raw help and description classes from rich_argparse
    """
    def __init__(self, prog):
        super().__init__(prog, width=4)

# Create parser with smaller width
smallwidthparser = argparse.ArgumentParser(formatter_class=SmallWidthFormmater)

for parser in [smallwidthparser]:
    # Add mutually exclusive group
    meg = parser.add_mutually_exclusive_group()
    # Add arguments to mutually exclusive group
    meg.add_argument(
        "--option1",
        metavar="metavar1",
        nargs="*",
    )
    meg.add_argument(
        "--option2",
        nargs=5,
    )
smallwidthparser.print_usage()
```

### Error output
This is the error-reproduction-script output :
Screenshot 2024-06-28 at 10 42 09 AM
As you can see the usage text does not get coloured.

### Reasons behind the error
The issue comes from **line 291** the `find_span` function:
https://github.com/hamdanal/rich-argparse/blob/89d5c268e18c01f961dc1554df63493168fc2fc2/rich_argparse/__init__.py#L291

Specifically, the `text` variable might have newline characters and spaces/tabs (I will refer to them as _indentation characters_) to properly indent the usage string. 
However, if the indentation characters are inserted within a metavar string (like it happens in the error reproduction case above, where the indentation characters are added between the `OPTION2` metavars) the `text.index(stripped, pos)` command will raise a `ValueError` because it will not find the exact metavar string.

### Solution
Instead of finding the index with `text.index(stripped, pos)` we need to use regex to find the index of "any string that  matches `stripped` with indentation characters in it".
This can be achieved by replacing `stripped` with the proper regex pattern, and find the start and end point through `re.finditer`.
I opened a PR with the implemented the solution.

### PR DESCRIPTION
**Pull request by atteggiani**
Fixes #125

### CODE REVIEW

**Comment by hamdanal** [comment]
Thanks, could you please add a test

**Comment by atteggiani** [comment]
Added a test for 100% coverage.

**Comment by hamdanal** [comment]
Something seems to work differently on Python 3.8 causing the test to fail. I can look into it later. Thanks for the PR.

**Comment by atteggiani** [comment]
> Something seems to work differently on Python 3.8 causing the test to fail. I can look into it later. Thanks for the PR.

Yeah apparently before `python3.9` the `nargs='*'` option would print different metavar output. 
You handle that in some other tests. I updated the PR and now it should work also for `python3.8`.

**Comment by hamdanal** [comment]
The test failure on 3.13 is due to a regression in CPython https://github.com/python/cpython/issues/121151. I am working on a fix upstream.

**Comment by atteggiani** [comment]
I see. 
For now we could place another conditional in the test that makes it work also with python 3.13, until there's a fix for the cpython bug.

**Comment by atteggiani** [comment]
Ok this is interesting. 
I am on a MacOS.

1. I tried running the test using the `python3.13.0b2` executable used by the CI run here and, as in the CI, it fails for the `test_usage_metavar_multiple_lines` function. 
2. I then tried running the test using a `python3.13.0a1` executable and the test fails for the `test_generated_usage` function, but not for the `test_usage_metavar_multiple_lines` one this time. 

Haven't dug deeper to understand the exact reasons behind this, but in general it means that even with the test modifications I was thinking about for `python3.13` there are still distributions (for example `python3.13.0a1`) that will fail the test.
For now I will place more specific conditionals for different releases, but maybe it's not the best solution in the long run.

**Comment by atteggiani** [comment]
Updated the test and now it should work also for `Python3.13`.

**Comment by atteggiani** [comment]
Closed as a new solution that fixes both #125 and #127 has been provided by @hamdanal [here](https://github.com/hamdanal/rich-argparse/issues/127#issuecomment-2198074148).

**Pull request closed without merging**
