### PR TITLE
Fix types and mark as typed

### PR DESCRIPTION
**Pull request by flying-sheep**
1. In order to make pyright/mypy identify this as typed, we need to add a `py.typed` file.
2. In order to add ti, we need to convert the module into a package.
3. In order to keep the `__main__` code working, it needs to live in a separate file.

Apart from this, I fixed the types: `group_name_formatter`, `styles`, `highlights`, and `usage_markup` are `ClassVar`s, not instance variables.

### CODE REVIEW

**Comment by hamdanal** [comment]
Thank you for your contribution and sorry I forgot to package the type information.

> 2. In order to add ti, we need to convert the module into a package

I would like to keep a single module though. Could you please revert converting the module into a package and I will make a separate PR to include type information in the PyPI distribution for the next release. Thanks

**Comment by flying-sheep** [comment]
I don’t quite understand what you mean.

I think we have two options here

1. ship an empty file called `rich_argparse/py.typed`
2. Change the build system so it creates a `rich_argparse.pyi` file next to the `rich_argparse.py` file.
3. Remember to manually recreate that .pyi file each time you upload a new version.

I think option 1 is by far the simplest

**Comment by hamdanal** [comment]
> I don’t quite understand what you mean.
> 
> I think we have two options here
> 
> 1. ship an empty file called `rich_argparse/py.typed`
> 2. Change the build system so it creates a `rich_argparse.pyi` file next to the `rich_argparse.py` file.
> 3. Remember to manually recreate that .pyi file each time you upload a new version.
> 
> I think option 1 is by far the simplest

Yes option 1 would be the simplest but as I said, I'd like to keep the single-module project. I can create a stub file and tell the build system to always include it in the wheel and sdist. This way the `rich_argparse.py` file stays and people can still copy it if they want to (it is a viable install option that I use all the time and it is [mentioned in the README](https://github.com/hamdanal/rich-argparse#installation)) and typing users will have their type checking work without complaints from mypy.

In this case if you just keep the fixes for the ClassVar attributes, I can merge this PR and then I can submit another PR with the new packaging and the stub file.

**Comment by hamdanal** [comment]
Thank you @flying-sheep for the report and fix. The next release (probably today) will be typed 🚀 .

**Pull request merged**
